name: python_shell
description: Python Environment Manager and Executor for dart and flutter
version: 0.0.2
repository: https://github.com/eseunghwan/python_shell.dart
issue_tracker: https://github.com/eseunghwan/python_shell.dart/issues

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.10.0"

platforms:
  macos:
  linux:
  windows:

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  flutter:
    sdk: flutter

  archive: ^3.3.1
  dio: ^4.0.6
  intl: ^0.17.0
  path: ^1.8.2
