name: python_shell
description: Python Environment Manager and Executor for dart and flutter
version: 0.0.7
repository: https://github.com/eseunghwan/python_shell.dart
issue_tracker: https://github.com/eseunghwan/python_shell.dart/issues

environment:
  sdk: '>=2.18.2 <3.0.0'

platforms:
  macos:
  linux:
  windows:

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.2
dependencies:
  archive: ^3.3.5
  dio: ^4.0.6
  intl: ^0.18.0
  path: ^1.8.3
